package com.guihuabao

class Caiwu {
    String cid
    String uid
    String begintime
    String endtime
    String n1
    String n2
    String n3
    String n4
    String m1
    String m2
    String m3
    String m4
    String m5
    String m6
    String m7
    String m8
    String m9
    String m10
    String m11
    String m12
    String m13
    String m14
    String m15
    String m16
    String m17
    String m18
    String m19
    String m20
    String m21
    String m22
    String m23

    String y1
    String y2
    String y3
    String y4
    String y5
    String y6
    String y7
    String y8
    String y9
    String y10
    String y11
    String y12
    String y13
    String y14
    String y15
    String y16
    String y17
    String y18
    String y19
    String y20
    String y21
    String y22
    String y23

    String p1
    String p2
    String p3
    String p4
    String p5
    String p6
    String p7
    String p8
    String p9
    String p10
    String p11
    String p12
    String p13
    String p14
    String p15
    String p16
    String p17
    String p18
    String p19
    String p20
    String p21
    String p22
    String p23

    String j1
    String j2
    String j3
    String j4
    String j5
    String j6
    String j7
    String j8
    String j9
    String j10
    String j11
    String j12
    String j13
    String j14
    String j15
    String j16
    String j17
    String j18
    String j19
    String j20
    String j21
    String j22
    String j23



    static constraints = {
         cid(nullable: true)
         uid(nullable: true)
         begintime(nullable: true)
         endtime(nullable: true)
         n1(nullable: true)
         n2(nullable: true)
         n3(nullable: true)
         n4(nullable: true)
         m1(nullable: true)
         m2(nullable: true)
         m3(nullable: true)
         m4(nullable: true)
         m5(nullable: true)
         m6(nullable: true)
         m7(nullable: true)
         m8(nullable: true)
         m9(nullable: true)
         m10(nullable: true)
         m11(nullable: true)
         m12(nullable: true)
         m13(nullable: true)
         m14(nullable: true)
         m15(nullable: true)
         m16(nullable: true)
         m17(nullable: true)
         m18(nullable: true)
         m19(nullable: true)
         m20(nullable: true)
         m21(nullable: true)
         m22(nullable: true)
         m23(nullable: true)

         y1(nullable: true)
        y2(nullable: true)
         y3(nullable: true)
         y4(nullable: true)
         y5(nullable: true)
         y6(nullable: true)
         y7(nullable: true)
         y8(nullable: true)
         y9(nullable: true)
         y10(nullable: true)
         y11(nullable: true)
         y12(nullable: true)
         y13(nullable: true)
         y14(nullable: true)
         y15(nullable: true)
         y16(nullable: true)
         y17(nullable: true)
         y18(nullable: true)
         y19(nullable: true)
         y20(nullable: true)
         y21(nullable: true)
         y22(nullable: true)
         y23(nullable: true)

         p1(nullable: true)
         p2(nullable: true)
         p3(nullable: true)
         p4(nullable: true)
         p5(nullable: true)
         p6(nullable: true)
         p7(nullable: true)
         p8(nullable: true)
         p9(nullable: true)
         p10(nullable: true)
         p11(nullable: true)
         p12(nullable: true)
         p13(nullable: true)
         p14(nullable: true)
         p15(nullable: true)
         p16(nullable: true)
         p17(nullable: true)
         p18(nullable: true)
         p19(nullable: true)
         p20(nullable: true)
         p21(nullable: true)
         p22(nullable: true)
         p23(nullable: true)

         j1(nullable: true)
         j2(nullable: true)
         j3(nullable: true)
         j4(nullable: true)
         j5(nullable: true)
         j6(nullable: true)
         j7(nullable: true)
         j8(nullable: true)
         j9(nullable: true)
         j10(nullable: true)
         j11(nullable: true)
         j12(nullable: true)
         j13(nullable: true)
         j14(nullable: true)
         j15(nullable: true)
         j16(nullable: true)
         j17(nullable: true)
         j18(nullable: true)
         j19(nullable: true)
         j20(nullable: true)
         j21(nullable: true)
         j22(nullable: true)
         j23(nullable: true)

    }
}
