package com.guihuabao

class Guimo {
    String cid
    String uid
    String begintime
    String endtime
    String jd1
    String jd2
    String jd3
    String jd4
    String jd5
    String jd6
    String jd7
    String jd8
//    String m11
//    String m12
    String m21
    String m22
    String m31
    String m32
    String m41
    String m42
    String m51
    String m52
    String m61
    String m62
    String m71
    String m72
    String m81
    String m82
    String m91
    String m92
    String m101
    String m102
    String m111
    String m112
    String m121
    String m122
    String m131
    String m132
    String m141
    String m142
    String m151
    String m152
    String m161
    String m162
    String m171
    String m172
    String m181
    String m182
    String m191
    String m192
    String m201
    String m202
    String m211
    String m212
    String m221
    String m222
    String m231
    String m232
    String m241
    String m242

    static constraints = {
        cid(nullable: true)
        uid(nullable: true)
        begintime(nullable: true)
        endtime(nullable: true)
        jd1(nullable: true)
        jd2(nullable: true)
        jd3(nullable: true)
        jd4(nullable: true)
        jd5(nullable: true)
        jd6(nullable: true)
        jd7(nullable: true)
        jd8(nullable: true)
        m21(nullable: true)
        m22(nullable: true)
        m31(nullable: true)
        m32(nullable: true)
        m41(nullable: true)
        m42(nullable: true)
        m51(nullable: true)
        m52(nullable: true)
        m61(nullable: true)
        m62(nullable: true)
        m71(nullable: true)
        m72(nullable: true)
        m81(nullable: true)
        m82(nullable: true)
        m91(nullable: true)
        m92(nullable: true)
        m101(nullable: true)
        m102(nullable: true)
        m111(nullable: true)
        m112(nullable: true)
        m121(nullable: true)
        m122(nullable: true)
        m131(nullable: true)
        m132(nullable: true)
        m141(nullable: true)
        m142(nullable: true)
        m151(nullable: true)
        m152(nullable: true)
        m161(nullable: true)
        m162(nullable: true)
        m171(nullable: true)
        m172(nullable: true)
        m181(nullable: true)
        m182(nullable: true)
        m191(nullable: true)
        m192(nullable: true)
        m201(nullable: true)
        m202(nullable: true)
        m211(nullable: true)
        m212(nullable: true)
        m221(nullable: true)
        m222(nullable: true)
        m231(nullable: true)
        m232(nullable: true)
        m241(nullable: true)
        m242(nullable: true)
    }
}
